import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "./AuthProvider";

export const metadata: Metadata = {
  title: "Finance App",
  description: "Generated by Caleffi Catalani",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-background antialiased`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
